import sharp from 'sharp';
import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import path from 'node:path';
const output='src/assets/optimized';
await mkdir(output,{recursive:true});
await mkdir('src/generated',{recursive:true});
await mkdir('static',{recursive:true});
const sources=[
 ['hero','src/assets/K-hero.webp',[480,800,960,1254]],
 ['smallDog','src/assets/img dog pequeno.png',[480,800,1254]],
 ['mediumDog','src/assets/img dog medio.png',[480,800,1254]],
 ['largeDog','src/assets/img dog grande.png',[480,800,1254]],
 ['simulator','src/assets/bg-simulador.png',[800,1200,1672]],
 ['logo','public/logo-horizontal.png',[192,384]],
 ...[1,2,3,4].map((n)=>[`layer${n}`,`src/assets/segundasecao/lamina-${n}-${['superficie','nucleo','barreira','base'][n-1]}.webp`,[480,640,960,1448]]),
 ...['pipizao','fofuxao','xixicao'].flatMap(line=>[7,30].map(units=>[`${line}${units}`,`public/produtos/${line}-${units}un.webp`,[480,900,1500]])),
];
const imports=[],entries=[],metadata=[];
for(const [id,source,requested] of sources){
 const input=await readFile(source);const meta=await sharp(input).metadata();
 const widths=[...new Set(requested.map(w=>Math.min(w,meta.width)))];
 const ratio=id==='layer1'?1.6:id==='layer2'?1.45:meta.width/meta.height;
 const variants=[];
 for(const width of widths){
  const height=Math.round(width/ratio),file=`${id}-${width}.webp`,dest=path.join(output,file);
  const options=id==='logo'?{lossless:true}:{quality:id==='hero'?88:82,effort:5};
  const fingerprint=createHash('sha256').update(input).update(JSON.stringify({width,height,options})).digest('hex');
  let unchanged=false;try{unchanged=(await readFile(dest+'.sha256','utf8'))===fingerprint;}catch{}
  if(!unchanged){await sharp(input).resize({width,height,fit:'fill'}).webp(options).toFile(dest);await writeFile(dest+'.sha256',fingerprint);}
  const name=`${id}_${width}`;imports.push(`import ${name} from '../assets/optimized/${file}';`);variants.push({name,width,height});
 }
 const main=variants.at(-1);
 entries.push(`  ${id}: { src: assetUrl(${main.name}), srcSet: [${variants.map(v=>`assetUrl(${v.name}) + ' ${v.width}w'`).join(', ')}].join(', '), width: ${main.width}, height: ${main.height} }`);
 metadata.push({id,source,variants:variants.map(v=>({width:v.width,height:v.height,file:`${id}-${v.width}.webp`}))});
}
await writeFile('src/generated/images.ts',`// Generated by npm run images. Edit scripts/generate-images.mjs instead.\nimport { assetUrl } from '../lib/image';\n${imports.join('\n')}\n\nexport const images = {\n${entries.join(',\n')}\n} as const;\n`);
await writeFile('src/generated/images-manifest.json',JSON.stringify(metadata,null,2)+'\n');
await sharp('public/favicon.png').resize(64,64).png().toFile('static/favicon.png');
await sharp('public/logo-horizontal.png').resize({width:768}).png().toFile('static/logo-kelka.png');
// Sharing artwork uses existing brand assets and live text, with no generated imagery.
const escape=s=>s.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('"','&quot;');
const background=Buffer.from(`<svg width="1200" height="630" xmlns="http://www.w3.org/2000/svg"><rect width="1200" height="630" fill="#00283b"/><circle cx="1030" cy="320" r="350" fill="#064961"/><text x="72" y="300" fill="#ffffff" font-family="sans-serif" font-size="54" font-weight="700">Mais absorção</text><text x="72" y="375" fill="#5ccda7" font-family="sans-serif" font-size="54" font-weight="700">Menos preocupação</text><text x="72" y="457" fill="#d0e5ee" font-family="sans-serif" font-size="27">${escape('Tapetes higiênicos para cães')}</text><text x="72" y="508" fill="#d0e5ee" font-family="sans-serif" font-size="22">Pipizão · Fofuxão · Xixicão</text></svg>`);
const logo=await sharp('public/logo-horizontal.png').resize({width:260}).png().toBuffer();
const hero=await sharp('src/assets/K-hero.webp').resize({width:500}).png().toBuffer();
await sharp(background).composite([{input:hero,left:710,top:100},{input:logo,left:72,top:74}]).jpeg({quality:88}).toFile('static/og-kelka.jpg');
console.log(`Generated ${sources.length} responsive image sets; originals preserved.`);
